apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discord-bot
  template:
    metadata:
      labels:
        app: discord-bot
    spec:
      containers:
      - name: discord-bot
        image: rg.pl-waw.scw.cloud/main-cr/discord-bot
        imagePullPolicy: Always
        livenessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 5
        env:
        - name: CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: secrets
              key: clientId
        - name: NODE_ENV
          value: "production"
        - name: REDIS_URL
          value: "redis://redis.default.svc.cluster.local:6379"
        - name: SENTRY_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: secrets
              key: sentryAuthToken
        - name: SENTRY_DSN
          valueFrom:
            secretKeyRef:
              name: secrets
              key: sentryDsn
        - name: TOKEN
          valueFrom:
            secretKeyRef:
              name: secrets
              key: token