name: Deploy
on:
  workflow_run:
    workflows: ["Lint"]
    branches: [main]
    types: 
      - completed
jobs:
  deploy:
    name: Build image and push to DOCR
    runs-on: ubuntu-latest
    concurrency: deploy-group # ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v4
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: |
          docker build -t registry.digitalocean.com/parsify-registry/discord-bot --build-arg SENTRY_AUTH_TOKEN=$SENTRY_AUTH_TOKEN .
          doctl registry login
          docker push registry.digitalocean.com/parsify-registry/discord-bot
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}