name: Deploy
on: push
jobs:
  docker:
    name: Build image and push it to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/arm64
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/arm64
          push: true
          tags: xxczaki/discord-bot:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          sbom: true
          secrets: |
            SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}
          build-args: |
            GIT_COMMIT_SHA=${{ github.sha }}
  github:
    name: Update image tag in xxczaki/argo-cd
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: xxczaki/argo-cd
          token: ${{ secrets.GH_PAT }}
      - name: Modify image tag
        env:
          TAG: ${{ github.sha }}
        run: |
          sed -i 's/image: .*/'"image: xxczaki\/discord-bot:$TAG/" ./discord-bot-deployment.yaml
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update xxczaki/discord-bot image tag