name: Deploy
on:
  workflow_run:
    workflows: ["Lint"]
    branches: [main]
    types: 
      - completed
jobs:
  deploy:
    name: Deploy with Fly.io
    runs-on: ubuntu-latest
    concurrency: deploy-group # ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only --env GIT_COMMIT=$(git rev-parse --short "$GITHUB_SHA") --build-secret SENTRY_RELEASE_NAME=$GITHUB_SHA --build-secret SENTRY_AUTH_TOKEN=$SENTRY_AUTH_TOKEN
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}