name: Deploy

on:
  workflow_run:
    workflows: ["Lint"]
    branches: [main]
    types: 
      - completed

jobs:
  docker:
    name: Build image and push it to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/arm64
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/arm64
          push: true
          tags: xxczaki/discord-bot:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          sbom: true
          secrets: |
            SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}
          build-args: |
            GIT_COMMIT_SHA=${{ github.sha }}
  helm:
    name: Update image tag in values.yaml and bump versions
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: docker
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Update image tag and appVersion
        uses: mikefarah/yq@master
        with:
          cmd: |
            yq -i '.tag = "${{ github.sha }}"' 'helm/discord-bot/values.yaml'
            yq -i '.appVersion = "${{ github.sha }}"' 'helm/discord-bot/Chart.yaml'
      - name: Get previous tag
        id: previousTag
        uses: WyriHaximus/github-action-get-previous-tag@v1
      - name: Get current version
        id: currentVersion
        uses: mikefarah/yq@master
        with:
          cmd: yq '.version' helm/discord-bot/Chart.yaml
      - name: Update chart version
        uses: mikefarah/yq@master
        if: steps.previousTag.outputs.tag == steps.currentVersion.outputs.result
        env:
          PREVIOUS_VERSION: ${{ steps.previousTag.outputs.tag }}
        with:
          cmd: |
            NEXT_VERSION=${PREVIOUS_VERSION%.*}.$((${PREVIOUS_VERSION##*.} + 1))
            yq -i '.version = $NEXT_VERSION' 'helm/discord-bot/values.yaml'
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update Helm chart