name: Deploy

on:
  workflow_run:
    workflows: ["Lint"]
    branches: [main]
    types: 
      - completed

jobs:
  docker:
    name: Build image and push it to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/arm64
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/arm64
          push: true
          tags: xxczaki/discord-bot:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          sbom: true
          secrets: |
            SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}
          build-args: |
            GIT_COMMIT_SHA=${{ github.sha }}
  helm:
    name: Update Helm chart in xxczaki/charts
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: xxczaki/charts
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0
      - name: Update image tag and appVersion
        uses: mikefarah/yq@master
        with:
          cmd: |
            yq -i '.image.tag = "${{ github.sha }}"' 'charts/discord-bot/values.yaml'
            yq -i '.appVersion = "${{ github.sha }}"' 'charts/discord-bot/Chart.yaml'
      - name: Get current version
        id: currentVersion
        uses: mikefarah/yq@master
        with:
          cmd: yq '.version' charts/discord-bot/Chart.yaml
      - name: Get previous tag
        id: previousTag
        uses: WyriHaximus/github-action-get-previous-tag@v1
        with:
          fallback: "discord-bot-${{ steps.currentVersion.outputs.result }}"
      - name: Update chart version
        uses: mikefarah/yq@master
        if: steps.previousTag.outputs.tag == "discord-bot-${{ steps.currentVersion.outputs.result }}"
        env:
          PREVIOUS_VERSION: ${{ steps.currentVersion.outputs.result }}
        with:
          cmd: NEXT_VERSION=${PREVIOUS_VERSION%.*}.$((${PREVIOUS_VERSION##*.} + 1)) yq -i '.version = strenv(NEXT_VERSION)' 'charts/discord-bot/Chart.yaml'
      - name: Import GPG key
        id: import-gpg
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update Helm chart
          commit_author: "${{ steps.import-gpg.outputs.name }} <${{ steps.import-gpg.outputs.email }}>"
          commit_user_name: ${{ steps.import-gpg.outputs.name }}
          commit_user_email: ${{ steps.import-gpg.outputs.email }}